### ISSUE TITLE
Swift 2 support

### ISSUE THREAD

**Issue by mac-cain13** [nomothetis/OptionKit#4]
Do you have any plans to update this to Swift 2? Would be very nice to use this in Swift 2 projects!

**Comment by kaandedeoglu** [comment]
+1 - I'd very much like to see this as well

**Comment by nomothetis** [comment]
Yes! I have been out on vacation and quite busy lately, but that's coming soon.

**Comment by mac-cain13** [comment]
Would be amazing, I'd love to use it in [R.swift](http://git.io/rswift)! :)

**Comment by nomothetis** [comment]
Great. I'll try to get that out this week. Also, I didn't even know about R.swift. I love it!
